### ISSUE TITLE
Examples Needed

### ISSUE THREAD

**Issue by goosehub** [GyunerZeki/APIJet#28]
I've been looking through the code for this repo and https://github.com/APIJet/skeleton, but I'm not understanding how I would make a basic API call. Can you provide at least 1 example in this repo or the other on how to do a very basic API call to a real route, such as merchant-skus?

**Comment by GyunerZeki** [comment]
Hey @goosehub 

If you use the Skeleton https://github.com/APIJet/skeleton you already have a default controllers/actions that you can call for testing purposes.  One of the example controllers is called Hello here is path to have a look at it https://github.com/APIJet/skeleton/blob/master/Controllers/Hello.php

Once you have that, now you can send API call from almost anything.

I will give you an example code, how to call this hello action with JS code, but if you need an example of specific language, let me know and I will try to provide an example on the language you need.

```
$.getJSON('https://yourdomainnamehere.com/hello_world/goose', function(response) {
	console.log(response);
});
```

Please let me know if that helps or you need extra information.

Have a fantastic weekend :)

Thanks,
Gyuner Zeki

**Comment by goosehub** [comment]
@GyunerZeki wait, is this an API for https://jet.com/ or is this just an API framework with jet in the name?

**Comment by GyunerZeki** [comment]
Hi @goosehub APIJet framework and this website jet.com are not related.  Just a name confusion.

**Comment by goosehub** [comment]
@GyunerZeki ah, that explains my confusion. Closing this issue.
